# Generated by Django 3.2.3 on 2021-05-21 20:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(help_text='Major category, for example Anime.', max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('source', models.URLField(default='')),
                ('credits', models.CharField(default='', max_length=64)),
                ('downloads', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EmojiLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('abbreviation', models.CharField(max_length=16, unique=True)),
                ('source_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('name', models.CharField(help_text='More specific, but still broad, version of category. Example anime show.', max_length=64, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subcategories', to='emoji_app.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='RecommendedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.SlugField(help_text='Recommend name for this emoji.', max_length=32, unique=True)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='emoji_app.emoji')),
            ],
            options={
                'ordering': ('weight',),
            },
        ),
        migrations.AddField(
            model_name='emoji',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarks', to='emoji_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='emojis', to='emoji_app.category'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='favored_by',
            field=models.ManyToManyField(related_name='favourites', to='emoji_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='emoji_app.emojilicense'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='emojis', to='emoji_app.subcategory'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_emojis', to='emoji_app.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='recommendedname',
            constraint=models.UniqueConstraint(fields=('emoji', 'name'), name='unique emoji name'),
        ),
    ]
