# Generated by Django 3.2.3 on 2021-05-22 23:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(help_text='Major category, for example Anime.', max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('downloads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(upload_to='static/')),
            ],
            options={
                'ordering': ('date_uploaded',),
            },
        ),
        migrations.CreateModel(
            name='EmojiLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('abbreviation', models.CharField(max_length=16, unique=True)),
                ('source_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('link', models.URLField(help_text='Link to copyright source.')),
                ('credits', models.TextField(blank=True, default='', help_text='Any additional credits.', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.SlugField(max_length=16, primary_key=True, serialize=False)),
                ('category', models.ManyToManyField(related_name='tags', to='emoji_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.SlugField(help_text='Recommend name for this emoji.', max_length=32)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='emoji_app.emoji')),
            ],
            options={
                'ordering': ('weight',),
            },
        ),
        migrations.AddField(
            model_name='emoji',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='emoji_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='emoji_app.emojilicense'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to='emoji_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emoji_app.source'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='tags',
            field=models.ManyToManyField(blank=True, to='emoji_app.Tag'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_emojis', to='emoji_app.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='recommendedname',
            constraint=models.UniqueConstraint(fields=('emoji', 'name'), name='unique emoji name'),
        ),
    ]
