# Generated by Django 3.2.3 on 2021-05-21 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarks', to='emoji_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='credits',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='downloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='favored_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourites', to='emoji_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='source',
            field=models.URLField(blank=True, default=''),
        ),
    ]
