# Generated by Django 5.0.3 on 2024-03-23 12:17

import chatvibes_app.models.validators
import chatvibes_app.storages
import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Copyright",
            fields=[
                (
                    "name",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("link", models.URLField(help_text="Link to copyright source.")),
                (
                    "credits",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Any additional credits.",
                        max_length=512,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "abbreviation",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "source_link",
                    models.URLField(help_text="Optional link to license description."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordClassification",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        validators=[chatvibes_app.models.validators.validate_word_name],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=1000),
                ),
                (
                    "order_sequence",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Visual order of word classifications will be based on this.",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="Visual color for this tag.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_write", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        storage=chatvibes_app.storages.get_storage, upload_to=""
                    ),
                ),
                (
                    "total_views",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("nsfw", models.BooleanField(default=False)),
                ("animated", models.BooleanField(default=False, editable=False)),
                (
                    "copyright",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="chatvibes_app.copyright",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="chatvibes_app.license",
                    ),
                ),
            ],
            options={
                "ordering": ("date_create",),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserImageReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for report.", max_length=512),
                ),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="chatvibes_app.image",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="chatvibes_app.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_write", models.DateTimeField(auto_now_add=True)),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Should it be visible on website or just for the user  that created it.",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="collections", to="chatvibes_app.image"
                    ),
                ),
                (
                    "create_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chatvibes_app.userprofile",
                    ),
                ),
                (
                    "write_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chatvibes_app.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="image",
            name="bookmarked_by",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarks", to="chatvibes_app.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="create_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chatvibes_app.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to="chatvibes_app.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="write_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chatvibes_app.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        validators=[chatvibes_app.models.validators.validate_word_name],
                    ),
                ),
                (
                    "is_lemma",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Does this word represent lemma of word, look up lemmatization.",
                    ),
                ),
                (
                    "related_lemma_word",
                    models.ForeignKey(
                        editable=False,
                        help_text="Related word that represents lemma word for this one.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="chatvibes_app.word",
                    ),
                ),
                (
                    "word_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="chatvibes_app.wordclassification",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(to="chatvibes_app.word"),
        ),
    ]
